//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.od;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for loadData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="loadData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ODConfig" type="{http://ws.ondemand.metlife.cl/}odConfig" minOccurs="0"/>
 *         &lt;element name="DataToLoad" type="{http://ws.ondemand.metlife.cl/}dataDescriptor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loadData", namespace = "http://ws.ondemand.metlife.cl/", propOrder = {
    "odConfig",
    "dataToLoad"
})
public class LoadData {

    @XmlElement(name = "ODConfig")
    protected OdConfig odConfig;
    @XmlElement(name = "DataToLoad")
    protected List<DataDescriptor> dataToLoad;

    /**
     * Gets the value of the odConfig property.
     * 
     * @return
     *     possible object is
     *     {@link OdConfig }
     *     
     */
    public OdConfig getODConfig() {
        return odConfig;
    }

    /**
     * Sets the value of the odConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdConfig }
     *     
     */
    public void setODConfig(OdConfig value) {
        this.odConfig = value;
    }

    /**
     * Gets the value of the dataToLoad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataToLoad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataToLoad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataDescriptor }
     * 
     * 
     */
    public List<DataDescriptor> getDataToLoad() {
        if (dataToLoad == null) {
            dataToLoad = new ArrayList<DataDescriptor>();
        }
        return this.dataToLoad;
    }

}
