//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.od;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.metlife.ws.clients.od package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LoadData_QNAME = new QName("http://ws.ondemand.metlife.cl/", "loadData");
    private final static QName _Exception_QNAME = new QName("http://ws.ondemand.metlife.cl/", "Exception");
    private final static QName _LoadDataResponse_QNAME = new QName("http://ws.ondemand.metlife.cl/", "loadDataResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.metlife.ws.clients.od
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoadData }
     * 
     */
    public LoadData createLoadData() {
        return new LoadData();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link DataDescriptor }
     * 
     */
    public DataDescriptor createDataDescriptor() {
        return new DataDescriptor();
    }

    /**
     * Create an instance of {@link Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link LoadDataResponse }
     * 
     */
    public LoadDataResponse createLoadDataResponse() {
        return new LoadDataResponse();
    }

    /**
     * Create an instance of {@link LoadResult }
     * 
     */
    public LoadResult createLoadResult() {
        return new LoadResult();
    }

    /**
     * Create an instance of {@link OdConfig }
     * 
     */
    public OdConfig createOdConfig() {
        return new OdConfig();
    }

    /**
     * Create an instance of {@link IndexList }
     * 
     */
    public IndexList createIndexList() {
        return new IndexList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ondemand.metlife.cl/", name = "loadData")
    public JAXBElement<LoadData> createLoadData(LoadData value) {
        return new JAXBElement<LoadData>(_LoadData_QNAME, LoadData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ondemand.metlife.cl/", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<Exception>(_Exception_QNAME, Exception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ondemand.metlife.cl/", name = "loadDataResponse")
    public JAXBElement<LoadDataResponse> createLoadDataResponse(LoadDataResponse value) {
        return new JAXBElement<LoadDataResponse>(_LoadDataResponse_QNAME, LoadDataResponse.class, null, value);
    }

}
