//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.od;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;

@WebService(name = "OnDemandLoader", targetNamespace = "http://ws.ondemand.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnDemandLoader {


    /**
     * 
     * @param odConfig
     * @param dataToLoad
     * @return
     *     returns cl.metlife.ws.clients.od.LoadResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadData", targetNamespace = "http://ws.ondemand.metlife.cl/", className = "cl.metlife.ws.clients.od.LoadData")
    @ResponseWrapper(localName = "loadDataResponse", targetNamespace = "http://ws.ondemand.metlife.cl/", className = "cl.metlife.ws.clients.od.LoadDataResponse")
    public LoadResult loadData(
            @WebParam(name = "ODConfig", targetNamespace = "")
                    OdConfig odConfig,
            @WebParam(name = "DataToLoad", targetNamespace = "")
                    List<DataDescriptor> dataToLoad)
        throws Exception_Exception
    ;

}
