//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.od;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

@WebServiceClient(name = "OnDemandLoaderService", targetNamespace = "http://ws.ondemand.metlife.cl/", wsdlLocation = "http://mlfdesibmarp:9080/OnDemandLoader/OnDemandLoaderService/OnDemandLoaderService.wsdl")
public class OnDemandLoaderService
    extends Service
{

    private final static URL ONDEMANDLOADERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.metlife.ws.clients.od.OnDemandLoaderService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.metlife.ws.clients.od.OnDemandLoaderService.class.getResource(".");
            url = new URL(baseUrl, "http://mlfdesibmarp:9080/OnDemandLoader/OnDemandLoaderService/OnDemandLoaderService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://mlfdesibmarp:9080/OnDemandLoader/OnDemandLoaderService/OnDemandLoaderService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ONDEMANDLOADERSERVICE_WSDL_LOCATION = url;
    }

    public OnDemandLoaderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnDemandLoaderService() {
        super(ONDEMANDLOADERSERVICE_WSDL_LOCATION, new QName("http://ws.ondemand.metlife.cl/", "OnDemandLoaderService"));
    }

    /**
     *
     * @return
     *     returns OnDemandLoader
     */
    @WebEndpoint(name = "OnDemandLoaderPort")
    public OnDemandLoader getOnDemandLoaderPort() {
        return super.getPort(new QName("http://ws.ondemand.metlife.cl/", "OnDemandLoaderPort"), OnDemandLoader.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnDemandLoader
     */
    @WebEndpoint(name = "OnDemandLoaderPort")
    public OnDemandLoader getOnDemandLoaderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ondemand.metlife.cl/", "OnDemandLoaderPort"), OnDemandLoader.class, features);
    }

}
