
package cl.metlife.ws.clients.saam.execution;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessExecution", targetNamespace = "http://printing.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessExecution {


    /**
     * 
     * @param arg2
     * @param processId
     * @param user
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "initProcess", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.saam.execution.InitProcess")
    @ResponseWrapper(localName = "initProcessResponse", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.saam.execution.InitProcessResponse")
    @Action(input = "http://printing.metlife.cl/ProcessExecution/initProcessRequest", output = "http://printing.metlife.cl/ProcessExecution/initProcessResponse")
    public Long initProcess(
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "arg2", targetNamespace = "")
        cl.metlife.ws.clients.saam.execution.InitProcess.Arg2 arg2);

    /**
     * 
     * @param forceData
     * @param processId
     * @param parameters
     * @param user
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "initProcessWithData", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.saam.execution.InitProcessWithData")
    @ResponseWrapper(localName = "initProcessWithDataResponse", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.saam.execution.InitProcessWithDataResponse")
    @Action(input = "http://printing.metlife.cl/ProcessExecution/initProcessWithDataRequest", output = "http://printing.metlife.cl/ProcessExecution/initProcessWithDataResponse")
    public Long initProcessWithData(
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "parameters", targetNamespace = "")
        cl.metlife.ws.clients.saam.execution.InitProcessWithData.Parameters parameters,
        @WebParam(name = "forceData", targetNamespace = "")
        List<StringArray> forceData);

}
