
package cl.metlife.ws.clients.saam.execution;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessExecutionService", targetNamespace = "http://printing.metlife.cl/", wsdlLocation = "http://localhost:9080/saam-services/ProcessExecutionService/ProcessExecutionService.wsdl")
public class ProcessExecutionService
    extends Service
{

    private final static URL PROCESSEXECUTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSEXECUTIONSERVICE_EXCEPTION;
    private final static QName PROCESSEXECUTIONSERVICE_QNAME = new QName("http://printing.metlife.cl/", "ProcessExecutionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/saam-services/ProcessExecutionService/ProcessExecutionService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSEXECUTIONSERVICE_WSDL_LOCATION = url;
        PROCESSEXECUTIONSERVICE_EXCEPTION = e;
    }

    public ProcessExecutionService() {
        super(__getWsdlLocation(), PROCESSEXECUTIONSERVICE_QNAME);
    }

    public ProcessExecutionService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSEXECUTIONSERVICE_QNAME);
    }

    public ProcessExecutionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns ProcessExecution
     */
    @WebEndpoint(name = "ProcessExecutionPort")
    public ProcessExecution getProcessExecutionPort() {
        return super.getPort(new QName("http://printing.metlife.cl/", "ProcessExecutionPort"), ProcessExecution.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessExecution
     */
    @WebEndpoint(name = "ProcessExecutionPort")
    public ProcessExecution getProcessExecutionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://printing.metlife.cl/", "ProcessExecutionPort"), ProcessExecution.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSEXECUTIONSERVICE_EXCEPTION!= null) {
            throw PROCESSEXECUTIONSERVICE_EXCEPTION;
        }
        return PROCESSEXECUTIONSERVICE_WSDL_LOCATION;
    }

}
