
package cl.metlife.ws.clients.altiuz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkerQuery", targetNamespace = "http://altiuz.cl/reports/definitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkerQuery {


    /**
     * 
     * @param queryRequest
     * @return
     *     returns cl.altiuz.arp.QueryResponse
     */
    @WebMethod(operationName = "Query")
    @WebResult(name = "QueryResponse", targetNamespace = "http://altiuz.cl/reports/schemas", partName = "QueryResponse")
    public QueryResponse query(
            @WebParam(name = "QueryRequest", targetNamespace = "http://altiuz.cl/reports/schemas", partName = "QueryRequest")
                    QueryRequest queryRequest);

}
