//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.timer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.metlife.ws.clients.timer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetTimer_QNAME = new QName("http://printing.metlife.cl/", "getTimer");
    private final static QName _GetTimerResponse_QNAME = new QName("http://printing.metlife.cl/", "getTimerResponse");
    private final static QName _ClearTimer_QNAME = new QName("http://printing.metlife.cl/", "clearTimer");
    private final static QName _GetNextExecutionForProcessResponse_QNAME = new QName("http://printing.metlife.cl/", "getNextExecutionForProcessResponse");
    private final static QName _ClearTimerResponse_QNAME = new QName("http://printing.metlife.cl/", "clearTimerResponse");
    private final static QName _GetNextExecutionForProcess_QNAME = new QName("http://printing.metlife.cl/", "getNextExecutionForProcess");
    private final static QName _SetTimer_QNAME = new QName("http://printing.metlife.cl/", "setTimer");
    private final static QName _SetTimerResponse_QNAME = new QName("http://printing.metlife.cl/", "setTimerResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.metlife.ws.clients.timer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTimer }
     * 
     */
    public GetTimer createGetTimer() {
        return new GetTimer();
    }

    /**
     * Create an instance of {@link GetNextExecutionForProcess }
     * 
     */
    public GetNextExecutionForProcess createGetNextExecutionForProcess() {
        return new GetNextExecutionForProcess();
    }

    /**
     * Create an instance of {@link SetTimer }
     * 
     */
    public SetTimer createSetTimer() {
        return new SetTimer();
    }

    /**
     * Create an instance of {@link GetNextExecutionForProcessResponse }
     * 
     */
    public GetNextExecutionForProcessResponse createGetNextExecutionForProcessResponse() {
        return new GetNextExecutionForProcessResponse();
    }

    /**
     * Create an instance of {@link GetTimerResponse }
     * 
     */
    public GetTimerResponse createGetTimerResponse() {
        return new GetTimerResponse();
    }

    /**
     * Create an instance of {@link ClearTimer }
     * 
     */
    public ClearTimer createClearTimer() {
        return new ClearTimer();
    }

    /**
     * Create an instance of {@link SetTimerResponse }
     * 
     */
    public SetTimerResponse createSetTimerResponse() {
        return new SetTimerResponse();
    }

    /**
     * Create an instance of {@link SimpleDisplayableTimer }
     * 
     */
    public SimpleDisplayableTimer createSimpleDisplayableTimer() {
        return new SimpleDisplayableTimer();
    }

    /**
     * Create an instance of {@link ClearTimerResponse }
     * 
     */
    public ClearTimerResponse createClearTimerResponse() {
        return new ClearTimerResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTimer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.metlife.cl/", name = "getTimer")
    public JAXBElement<GetTimer> createGetTimer(GetTimer value) {
        return new JAXBElement<GetTimer>(_GetTimer_QNAME, GetTimer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTimerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.metlife.cl/", name = "getTimerResponse")
    public JAXBElement<GetTimerResponse> createGetTimerResponse(GetTimerResponse value) {
        return new JAXBElement<GetTimerResponse>(_GetTimerResponse_QNAME, GetTimerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearTimer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.metlife.cl/", name = "clearTimer")
    public JAXBElement<ClearTimer> createClearTimer(ClearTimer value) {
        return new JAXBElement<ClearTimer>(_ClearTimer_QNAME, ClearTimer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNextExecutionForProcessResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.metlife.cl/", name = "getNextExecutionForProcessResponse")
    public JAXBElement<GetNextExecutionForProcessResponse> createGetNextExecutionForProcessResponse(GetNextExecutionForProcessResponse value) {
        return new JAXBElement<GetNextExecutionForProcessResponse>(_GetNextExecutionForProcessResponse_QNAME, GetNextExecutionForProcessResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearTimerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.metlife.cl/", name = "clearTimerResponse")
    public JAXBElement<ClearTimerResponse> createClearTimerResponse(ClearTimerResponse value) {
        return new JAXBElement<ClearTimerResponse>(_ClearTimerResponse_QNAME, ClearTimerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNextExecutionForProcess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.metlife.cl/", name = "getNextExecutionForProcess")
    public JAXBElement<GetNextExecutionForProcess> createGetNextExecutionForProcess(GetNextExecutionForProcess value) {
        return new JAXBElement<GetNextExecutionForProcess>(_GetNextExecutionForProcess_QNAME, GetNextExecutionForProcess.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetTimer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.metlife.cl/", name = "setTimer")
    public JAXBElement<SetTimer> createSetTimer(SetTimer value) {
        return new JAXBElement<SetTimer>(_SetTimer_QNAME, SetTimer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetTimerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.metlife.cl/", name = "setTimerResponse")
    public JAXBElement<SetTimerResponse> createSetTimerResponse(SetTimerResponse value) {
        return new JAXBElement<SetTimerResponse>(_SetTimerResponse_QNAME, SetTimerResponse.class, null, value);
    }

}
