//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.timer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ProcessTimerService", targetNamespace = "http://printing.metlife.cl/", wsdlLocation = "http://mlfsoaqat01.alico.corp:9080/saam-services/ProcessTimerService/ProcessTimerService.wsdl")
public class ProcessTimerService
    extends Service
{

    private final static URL PROCESSTIMERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.metlife.ws.clients.timer.ProcessTimerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.metlife.ws.clients.timer.ProcessTimerService.class.getResource(".");
            url = new URL(baseUrl, "http://mlfsoaqat01.alico.corp:9080/saam-services/ProcessTimerService/ProcessTimerService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://mlfsoaqat01.alico.corp:9080/saam-services/ProcessTimerService/ProcessTimerService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROCESSTIMERSERVICE_WSDL_LOCATION = url;
    }

    public ProcessTimerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessTimerService(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://printing.metlife.cl/", "ProcessTimerService"));
    }

    public ProcessTimerService() {
        super(PROCESSTIMERSERVICE_WSDL_LOCATION, new QName("http://printing.metlife.cl/", "ProcessTimerService"));
    }

    /**
     * 
     * @return
     *     returns ProcessTimer
     */
    @WebEndpoint(name = "ProcessTimerPort")
    public ProcessTimer getProcessTimerPort() {
        return super.getPort(new QName("http://printing.metlife.cl/", "ProcessTimerPort"), ProcessTimer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessTimer
     */
    @WebEndpoint(name = "ProcessTimerPort")
    public ProcessTimer getProcessTimerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://printing.metlife.cl/", "ProcessTimerPort"), ProcessTimer.class, features);
    }

}
