//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.timer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ProcessTimer", targetNamespace = "http://printing.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessTimer {


    /**
     * 
     * @param processId
     * @return
     *     returns cl.metlife.ws.clients.timer.SimpleDisplayableTimer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimer", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.timer.GetTimer")
    @ResponseWrapper(localName = "getTimerResponse", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.timer.GetTimerResponse")
    public SimpleDisplayableTimer getTimer(
        @WebParam(name = "processId", targetNamespace = "")
        Long processId);

    /**
     * 
     * @param processId
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNextExecutionForProcess", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.timer.GetNextExecutionForProcess")
    @ResponseWrapper(localName = "getNextExecutionForProcessResponse", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.timer.GetNextExecutionForProcessResponse")
    public XMLGregorianCalendar getNextExecutionForProcess(
        @WebParam(name = "processId", targetNamespace = "")
        Long processId);

    /**
     * 
     * @param processId
     * @param scheduleExpression
     */
    @WebMethod
    @RequestWrapper(localName = "setTimer", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.timer.SetTimer")
    @ResponseWrapper(localName = "setTimerResponse", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.timer.SetTimerResponse")
    public void setTimer(
        @WebParam(name = "scheduleExpression", targetNamespace = "")
        SimpleDisplayableTimer scheduleExpression,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId);

    /**
     * 
     * @param processId
     */
    @WebMethod
    @RequestWrapper(localName = "clearTimer", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.timer.ClearTimer")
    @ResponseWrapper(localName = "clearTimerResponse", targetNamespace = "http://printing.metlife.cl/", className = "cl.metlife.ws.clients.timer.ClearTimerResponse")
    public void clearTimer(
        @WebParam(name = "processId", targetNamespace = "")
        Long processId);

}
