//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.timer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for setTimer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="setTimer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scheduleExpression" type="{http://printing.metlife.cl/}simpleDisplayableTimer" minOccurs="0"/>
 *         &lt;element name="processId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setTimer", namespace = "http://printing.metlife.cl/", propOrder = {
    "scheduleExpression",
    "processId"
})
public class SetTimer {

    protected SimpleDisplayableTimer scheduleExpression;
    protected Long processId;

    /**
     * Gets the value of the scheduleExpression property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleDisplayableTimer }
     *     
     */
    public SimpleDisplayableTimer getScheduleExpression() {
        return scheduleExpression;
    }

    /**
     * Sets the value of the scheduleExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleDisplayableTimer }
     *     
     */
    public void setScheduleExpression(SimpleDisplayableTimer value) {
        this.scheduleExpression = value;
    }

    /**
     * Gets the value of the processId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProcessId() {
        return processId;
    }

    /**
     * Sets the value of the processId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProcessId(Long value) {
        this.processId = value;
    }

}
